name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          lfs: true 

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rm -rf .git
          git init
          git lfs install
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Sync from GitHub"
          git push --force https://agustinah:$HF_TOKEN@huggingface.co/spaces/agustinah/airline-satisfaction HEAD:main
